### ISSUE TITLE
An error occurred during installation

### ISSUE THREAD

**Issue by luckyaduGithub** [nagadomi/nunif#135]
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "runpy.py", line 187, in _run_module_as_main
  File "runpy.py", line 110, in _get_module_details
  File "J:\iw3\nunif\waifu2x\__init__.py", line 1, in <module>
    from .utils import Waifu2x
  File "J:\iw3\nunif\waifu2x\utils.py", line 5, in <module>
    from nunif.transforms.tta import tta_merge, tta_split
  File "J:\iw3\nunif\nunif\__init__.py", line 3, in <module>
    from . import transforms
  File "J:\iw3\nunif\nunif\transforms\__init__.py", line 1, in <module>
    from .std import (
  File "J:\iw3\nunif\nunif\transforms\std.py", line 2, in <module>
    from torchvision import transforms as T
  File "J:\iw3\python\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "J:\iw3\python\lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "J:\iw3\python\lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "J:\iw3\python\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from ._register_onnx_ops import _register_custom_op
  File "J:\iw3\python\lib\site-packages\torchvision\ops\_register_onnx_ops.py", line 5, in <module>
    from torch.onnx import symbolic_opset11 as opset11
  File "J:\iw3\python\lib\site-packages\torch\onnx\__init__.py", line 59, in <module>
    from ._internal.onnxruntime import (
  File "J:\iw3\python\lib\site-packages\torch\onnx\_internal\onnxruntime.py", line 37, in <module>
    import onnxruntime  # type: ignore[import]
  File "J:\iw3\python\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "J:\iw3\python\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "runpy.py", line 187, in _run_module_as_main
  File "runpy.py", line 110, in _get_module_details
  File "J:\iw3\nunif\waifu2x\__init__.py", line 1, in <module>
    from .utils import Waifu2x
  File "J:\iw3\nunif\waifu2x\utils.py", line 5, in <module>
    from nunif.transforms.tta import tta_merge, tta_split
  File "J:\iw3\nunif\nunif\__init__.py", line 3, in <module>
    from . import transforms
  File "J:\iw3\nunif\nunif\transforms\__init__.py", line 1, in <module>
    from .std import (
  File "J:\iw3\nunif\nunif\transforms\std.py", line 2, in <module>
    from torchvision import transforms as T
  File "J:\iw3\python\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "J:\iw3\python\lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "J:\iw3\python\lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "J:\iw3\python\lib\site-packages\torchvision\ops\__init__.py", line 23, in <module>
    from .poolers import MultiScaleRoIAlign
  File "J:\iw3\python\lib\site-packages\torchvision\ops\poolers.py", line 10, in <module>
    from .roi_align import roi_align
  File "J:\iw3\python\lib\site-packages\torchvision\ops\roi_align.py", line 4, in <module>
    import torch._dynamo
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\__init__.py", line 64, in <module>
    torch.manual_seed = disable(torch.manual_seed)
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\decorators.py", line 50, in disable
    return DisableContext()(fn)
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\eval_frame.py", line 410, in __call__
    (filename is None or trace_rules.check(fn))
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\trace_rules.py", line 3378, in check
    return check_verbose(obj, is_inlined_call).skipped
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\trace_rules.py", line 3361, in check_verbose
    rule = torch._dynamo.trace_rules.lookup_inner(
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\trace_rules.py", line 3442, in lookup_inner
    rule = get_torch_obj_rule_map().get(obj, None)
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\trace_rules.py", line 2782, in get_torch_obj_rule_map
    obj = load_object(k)
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\trace_rules.py", line 2811, in load_object
    val = _load_obj_from_str(x[0])
  File "J:\iw3\python\lib\site-packages\torch\_dynamo\trace_rules.py", line 2795, in _load_obj_from_str
    return getattr(importlib.import_module(module), obj_name)
  File "importlib\__init__.py", line 126, in import_module
  File "J:\iw3\python\lib\site-packages\torch\nested\_internal\nested_tensor.py", line 417, in <module>
    values=torch.randn(3, 3, device="meta"),
J:\iw3\python\lib\site-packages\torch\nested\_internal\nested_tensor.py:417: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  values=torch.randn(3, 3, device="meta"),

**Comment by luckyaduGithub** [comment]
![微信截图_20240617114031](https://github.com/nagadomi/nunif/assets/127811938/8fb966fd-27ff-4c7e-b7ab-79ac2496ca47)

**Comment by nagadomi** [comment]
Fixed https://github.com/nagadomi/nunif/commit/69ae9a1d0e8ee596844f977743ff814fc3647daa. Try to run `update.bat` again.

**Comment by luckyaduGithub** [comment]
> Fixed [69ae9a1](https://github.com/nagadomi/nunif/commit/69ae9a1d0e8ee596844f977743ff814fc3647daa). Try to run `update.bat` again.

Thanks for the instant fix, awesome!
