### ISSUE TITLE
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: './data/waifu2x\\train'

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#15]
(nunif) F:\nunif>python train.py waifu2x --method scale --arch waifu2x.upcunet --data-dir ./data/waifu2x --model-dir ./models/waifu2x_mymodel
{'amp_float': 'fp16',
 'arch': 'waifu2x.upcunet',
 'b4b': False,
 'batch_size': 16,
 'checkpoint_file': None,
 'da_chshuf_p': 0.0,
 'da_grayscale_p': 0.0,
 'da_jpeg_p': 0.0,
 'da_scale_p': 0.25,
 'da_unsharpmask_p': 0.0,
 'data_dir': './data/waifu2x',
 'deblur': 0.0,
 'disable_amp': False,
 'gpu': [0],
 'handler': <function train at 0x000001E6D29E08B0>,
 'hard_example': 'linear',
 'learning_rate': 0.0002,
 'learning_rate_cycles': 5,
 'learning_rate_decay': 0.995,
 'learning_rate_decay_step': [1],
 'loss': None,
 'max_epoch': 200,
 'method': 'scale',
 'model_dir': './models/waifu2x_mymodel',
 'momentum': 0.9,
 'noise_level': None,
 'num_samples': 50000,
 'num_workers': 2,
 'optimizer': 'adamw',
 'prefetch_factor': 4,
 'reset_state': False,
 'resize_blur_p': 0.1,
 'resume': False,
 'scheduler': 'cosine',
 'seed': 71,
 'size': 112,
 'style': 'art',
 'warmup_epoch': 0,
 'warmup_learning_rate': 1e-06,
 'weight_decay': 0.001}
Traceback (most recent call last):
  File "F:\nunif\train.py", line 22, in <module>
    main()
  File "F:\nunif\train.py", line 18, in main
    args.handler(args)
  File "F:\nunif\waifu2x\training\trainer.py", line 198, in train
    trainer.fit()
  File "F:\nunif\nunif\training\trainer.py", line 77, in fit
    self.initialize()
  File "F:\nunif\nunif\training\trainer.py", line 35, in initialize
    self.train_loader = self.create_dataloader(type="train")
  File "F:\nunif\waifu2x\training\trainer.py", line 58, in create_dataloader
    dataset = Waifu2xDataset(
  File "F:\nunif\waifu2x\training\dataset.py", line 169, in __init__
    super().__init__(input_dir, num_samples=num_samples)
  File "F:\nunif\waifu2x\training\dataset.py", line 113, in __init__
    self.files = ImageLoader.listdir(input_dir)
  File "F:\nunif\nunif\utils\image_loader.py", line 42, in listdir
    return list_images(directory)
  File "F:\nunif\nunif\utils\image_loader.py", line 34, in list_images
    for f in os.listdir(directory)
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: './data/waifu2x\\train'

**Comment by nagadomi** [comment]
same as https://github.com/nagadomi/nunif/issues/14
