### ISSUE TITLE
How do I launch my own model?

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#22]
How do I launch my own model? Located in F:\nunif\models\waifu2x_mymodel

**Comment by nagadomi** [comment]
For CLI, use `--model-dir` to specify the model directory.
example
```
python -m waifu2x.cli --model-dir F:\nunif\models\waifu2x_mymodel -m scale -i input_image_or_dir.png -o output_image_or_dir.png
```
For waifu2x.web, use `--art-model-dir` or `--photo-model-dir` to specify the model directory.
However, the directory used by waifu2x.web must have all the noise level model files.
So I would suggest making a copy of `waifu2x/pretrained_models/cunet/art` first, overwriting the trained model there, and then specifying it.

**Comment by My12123** [comment]
(nunif) F:\nunif>python -m waifu2x.cli --model-dir F:\nunif\models\waifu2x_mymodel -m scale -i F:\Загрузки\poster_1521773665852.jpg -o F:\Загрузки\3\poster_1521773665852.jpg
Traceback (most recent call last):
  File "F:\1\envs\nunif\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\1\envs\nunif\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\nunif\waifu2x\cli.py", line 157, in <module>
    main(args)
  File "F:\nunif\waifu2x\cli.py", line 107, in main
    ctx.load_model(args.method, args.noise_level)
  File "F:\nunif\waifu2x\utils.py", line 128, in load_model
    self._load_model(method, noise_level)
  File "F:\nunif\waifu2x\utils.py", line 76, in _load_model
    self.scale_model, _ = load_model(
  File "F:\nunif\nunif\models\utils.py", line 50, in load_model
    model = create_model(data["name"], device_ids=device_ids, **data["kwargs"])
  File "F:\nunif\nunif\models\register.py", line 38, in create_model
    raise ValueError(f"Unknown model name: {name}")
ValueError: Unknown model name: waifu2x.upcunet
