### ISSUE TITLE
Is there a way to install web server on Raspberry Pi 5?

### ISSUE THREAD

**Issue by Ives-Natsume** [nagadomi/nunif#225]
Hardware: Raspberry Pi 5 8GB RAM
OS: Ubuntu server 22.04 LST

Hi, I'm going to build the service on my Pi 5 (8GB RAM), which should not have CUDA support, thus I tried to build `Dockerfile.cpu_noavx`,
but failures on package installation kept happening.

```
(Waifu2x) metasequoiani@ubuntu:~/server/nunif-master$ docker build -t nunif -f Dockerfiles/Dockerfile.cpu_noavx Dockerfiles
[+] Building 0.6s (6/19)                                                docker:default
 => [internal] load build definition from Dockerfile.cpu_noavx                    0.0s
 => => transferring dockerfile: 2.19kB                                            0.0s
 => WARN: MaintainerDeprecated: Maintainer instruction is deprecated in favor of  0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.8.0-runtime-ubuntu22.0  0.0s
 => [internal] load .dockerignore                                                 0.0s
 => => transferring context: 2B                                                   0.0s
 => [ 1/16] FROM docker.io/nvidia/cuda:11.8.0-runtime-ubuntu22.04                 0.0s
 => CACHED [ 2/16] RUN apt-get update -y                                          0.0s
 => ERROR [ 3/16] RUN apt-get install -y     git python3-pip libmagickwand-dev l  0.4s
------
 > [ 3/16] RUN apt-get install -y     git python3-pip libmagickwand-dev libraqm-dev     wget libomp-dev libopenblas-dev gfortran libblas-dev     m4 cmake python3-dev python3-yaml python3-setuptools ninja-build:
0.231 Reading package lists...
0.248 Building dependency tree...
0.249 Reading state information...
0.249 E: Unable to locate package git
0.249 E: Unable to locate package python3-pip
0.249 E: Unable to locate package libmagickwand-dev
0.249 E: Unable to locate package libraqm-dev
0.249 E: Unable to locate package wget
0.249 E: Unable to locate package libomp-dev
0.249 E: Unable to locate package libopenblas-dev
0.249 E: Unable to locate package gfortran
0.249 E: Unable to locate package libblas-dev
0.249 E: Unable to locate package m4
0.249 E: Unable to locate package cmake
0.249 E: Unable to locate package python3-dev
0.249 E: Unable to locate package python3-yaml
0.249 E: Unable to locate package python3-setuptools
0.249 E: Unable to locate package ninja-build
------

 1 warning found (use docker --debug to expand):
 - MaintainerDeprecated: Maintainer instruction is deprecated in favor of using label (line 5)
Dockerfile.cpu_noavx:12
--------------------
  11 |     RUN apt-get update -y
  12 | >>> RUN apt-get install -y \
  13 | >>>     git python3-pip libmagickwand-dev libraqm-dev \
  14 | >>>     wget libomp-dev libopenblas-dev gfortran libblas-dev \
  15 | >>>     m4 cmake python3-dev python3-yaml python3-setuptools ninja-build
  16 |
--------------------
ERROR: failed to solve: process "/bin/bash -c apt-get install -y     git python3-pip libmagickwand-dev libraqm-dev     wget libomp-dev libopenblas-dev gfortran libblas-dev     m4 cmake python3-dev python3-yaml python3-setuptools ninja-build" did not complete successfully: exit code: 100
```
And when I following your `INSTALL-ubuntu.md`, I got stuck on `pip3 install -r requirements-torch.txt`
```
ERROR: Could not find a version that satisfies the requirement torch==2.4.0+cu118 (from versions: none)
ERROR: No matching distribution found for torch==2.4.0+cu118
```
So what could I do to solve the problem? Thank you :)

**Comment by nagadomi** [comment]
For Docker, it seems that `apt-get install` command has failed for all packages on guest Ubuntu OS. Maybe it is caused by CPU arch.

Could you try to install without Docker?
I have confirmed that it works with Raspberry Pi3 aarch64 in the past.

>And when I following your INSTALL-ubuntu.md, I got stuck on pip3 install -r requirements-torch.txt

You can install torch for aarch64 with the following command.
```
pip3 install torch torchvision
```

If you encounter any errors, try the following.
```
pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
```

**Comment by Ives-Natsume** [comment]
hi, I will try it later, hope it works

**Comment by Ives-Natsume** [comment]
Hi, thankfully your advise works very well :)
But sadly due to some reason I failed to run `python3 -m waifu2x.download_models`, which says 
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: 
/nagadomi/nunif/releases/download/0.0.0/waifu2x_pretrained_models_20230504.zip 
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff6992e030>: 
Failed to establish a new connection: [Errno 113] No route to host'))
```
I guess it was because the url should be `https://github.com/nagadomi/......`, but anyway I downloaded the pre-trained model manually. So which path should I save the model? And should I unzip the model?
Many thanks

**Comment by nagadomi** [comment]
Unzip `waifu2x_pretrained_models_20230504.zip` and you will find the directory `pretrained_models`.
Put it in `waifu2x/pretrained_models`.
```
% tree -d waifu2x/pretrained_models
waifu2x/pretrained_models
├── cunet
│   └── art
├── swin_unet
│   ├── art
│   ├── art_scan
│   └── photo
└── upconv_7
    ├── art
    └── photo

```

>Failed to establish a new connection: [Errno 113] No route to host'

The error is most likely caused by DNS setting or firewall. If the device has internet connection.

**Comment by Ives-Natsume** [comment]
Hi, I'm close to success now. The server started successfully but quickly throw errors:
```
(Waifu2x) metasequoiani@ubuntu:~/server/nunif-master$ python -m waifu2x.web
Bottle v0.13.1 server starting up (using WaitressServer(preload_app=True, threads=32, outbuf_overflow=20971520, inbuf_overflow=20971520, max_request_body_size=5242880, connection_limit=256, channel_timeout=120))...
Listening on http://127.0.0.1:8812/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/metasequoiani/server/nunif-master/waifu2x/web/__main__.py", line 15, in <module>
    main()
  File "/home/metasequoiani/server/nunif-master/waifu2x/web/server.py", line 538, in main
    bottle.run(host=command_args.bind_addr, port=command_args.port, debug=command_args.debug,
  File "/home/metasequoiani/env/miniforge3/envs/Waifu2x/lib/python3.12/site-packages/bottle.py", line 3983, in run
    server.run(app)
  File "/home/metasequoiani/env/miniforge3/envs/Waifu2x/lib/python3.12/site-packages/bottle.py", line 3587, in run
    serve(handler, host=self.host, port=self.port, _quiet=self.quiet, **self.options)
  File "/home/metasequoiani/env/miniforge3/envs/Waifu2x/lib/python3.12/site-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
             ^^^^^^^^^^^^^^^^^^
  File "/home/metasequoiani/env/miniforge3/envs/Waifu2x/lib/python3.12/site-packages/waitress/server.py", line 49, in create_server
    adj = Adjustments(**kw)
          ^^^^^^^^^^^^^^^^^
  File "/home/metasequoiani/env/miniforge3/envs/Waifu2x/lib/python3.12/site-packages/waitress/adjustments.py", line 318, in __init__
    raise ValueError("Unknown adjustment %r" % k)
ValueError: Unknown adjustment 'preload_app'
```
Is it caused by my python version? I'm currently running server on python 3.12

**Comment by nagadomi** [comment]
It seems to be caused by the recently released bottle 0.13.1.
You can fix it with the following commands for now.
```
pip3 install bottle==0.12.25
```

**Comment by Ives-Natsume** [comment]
Many thanks! The server runs properly on my pi now. Later I'll try to publish the server onto my nginx for local network service.
And one more question: Will the server automatically delete the photo from memory which has finished upscaling?
Thank you for all your help :)

**Comment by nagadomi** [comment]
Some images(Images fetched from URL and converted images) are cached for 30 minutes by default.
You can change the Cache Time to Live with the following options
```
 --cache-ttl CACHE_TTL
                        cache TTL(min) (default: 30)
```
Image cache is stored in `tmp/waifu2x_cache`. However, it cannot be viewed by normal image viewers.

**Comment by Ives-Natsume** [comment]
I see. Many thanks for your great work!
