### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#26]
Traceback (most recent call last):
  File "C:\nunif\train.py", line 22, in <module>
    main()
  File "C:\nunif\train.py", line 18, in main
    args.handler(args)
  File "C:\nunif\waifu2x\training\train.py", line 37, in train
    trainer.fit()
  File "C:\nunif\nunif\training\trainer.py", line 114, in fit
    self.env.train(
  File "C:\nunif\nunif\training\env.py", line 141, in train
    self.train_backward_step(loss, optimizers, grad_scaler,
  File "C:\nunif\waifu2x\training\trainer.py", line 222, in train_backward_step
    super().train_backward_step(loss, optimizers, grad_scaler, update)
  File "C:\nunif\nunif\training\env.py", line 63, in train_backward_step
    self.optimizer_step(optimizers, grad_scaler)
  File "C:\nunif\nunif\training\env.py", line 52, in optimizer_step
    grad_scaler.step(optimizer)
  File "F:\1\envs\nunif\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "F:\1\envs\nunif\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 287, in _maybe_opt_step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "F:\1\envs\nunif\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 287, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
KeyboardInterrupt

**Comment by nagadomi** [comment]
This error occurs when you interrupt the program by pressing Ctrl+C (on windows Ctrl+Break).

**Comment by My12123** [comment]
Can this be fixed? So that there is no error, but there is an exit from the program.

**Comment by nagadomi** [comment]
At the moment, I do not believe graceful shutdown is needed.
That is a pain to implement in multi-threaded/multi-process environment, and there is no advantage to me if that feature is implemented.
