### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 19992) exited unexpectedly

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#27]
```python
epoch: 20, lr: [[0.000108, 0.000108]]
--
 train
100%|████████████████████████████████████| 3125/3125 [12:32:02<00:00, 14.44s/it]
loss: 0.041987
--
 eval
 44%|██████████████████▏                      | 293/659 [07:15<09:03,  1.48s/it]
Traceback (most recent call last):
  File "F:\1\envs\nunif\lib\site-packages\torch\utils\data\dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "F:\1\envs\nunif\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\nunif\train.py", line 22, in <module>
    main()
  File "C:\nunif\train.py", line 18, in main
    args.handler(args)
  File "C:\nunif\waifu2x\training\train.py", line 37, in train
    trainer.fit()
  File "C:\nunif\nunif\training\trainer.py", line 122, in fit
    loss = self.env.eval(self.eval_loader)
  File "C:\nunif\nunif\training\env.py", line 152, in eval
    for data in tqdm(loader, ncols=80):
  File "F:\1\envs\nunif\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "F:\1\envs\nunif\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "F:\1\envs\nunif\lib\site-packages\torch\utils\data\dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "F:\1\envs\nunif\lib\site-packages\torch\utils\data\dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "F:\1\envs\nunif\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 19992) exited unexpectedly
``` 
Training was suspended by highlighting the console text.

**Comment by nagadomi** [comment]
Windows command prompt suspends the program during text selection.
At that time, there may be a problem with PyTorch's data loader process.

well, it is a Windows or PyTorch problem, so I cannot fix it on my side.

Also, disabling QuickEdit Mode may prevent this problem. 
See https://superuser.com/questions/555160/windows-command-prompt-freezing-on-focus
