### ISSUE TITLE
Uses a lot of memory.

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#31]
![2023-04-24_22-07-53](https://user-images.githubusercontent.com/49092250/234093456-ca45a005-f4f1-4c69-86b4-43ea96fc7e35.png)
![2023-04-24_22-11-13](https://user-images.githubusercontent.com/49092250/234093459-113f9f44-5363-4ae7-b345-22194dbb7775.png)
![2023-04-24_22-13-01](https://user-images.githubusercontent.com/49092250/234093473-7fb3cde4-440a-48a7-aae2-6cc028a10586.png)
```python
(nunif) C:\nunif>python -m waifu2x.web --no-size-limit
Traceback (most recent call last):
  File "F:\3\envs\nunif\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\3\envs\nunif\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\nunif\waifu2x\web\__main__.py", line 9, in <module>
    from .server import main
  File "C:\nunif\waifu2x\web\server.py", line 146, in <module>
    command_args, config, art_ctx, photo_ctx, cache, cache_gc = setup()
  File "C:\nunif\waifu2x\web\server.py", line 128, in setup
    art_ctx.load_model_all(load_4x=False)
  File "C:\nunif\waifu2x\utils.py", line 155, in load_model_all
    self._load_model("noise", noise_level)
  File "C:\nunif\waifu2x\utils.py", line 111, in _load_model
    self.noise_models[noise_level], _ = load_model(
  File "C:\nunif\nunif\models\utils.py", line 50, in load_model
    model = create_model(data["name"], device_ids=device_ids, **data["kwargs"])
  File "C:\nunif\nunif\models\register.py", line 54, in create_model
    model = model.to(device)
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 8.00 GiB total capacity; 43.94 MiB already allocated; 0 bytes free; 44.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CON
```

**Comment by nagadomi** [comment]
It may be caused by other processes that use a lot of GPU memory, such as waifu2x training process or other AI projects.
Make sure that there are no other GPU processes running at the same time.

**Comment by My12123** [comment]
```python
(nunif) C:\nunif>python -m waifu2x.web
Traceback (most recent call last):
  File "F:\3\envs\nunif\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "F:\3\envs\nunif\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\nunif\waifu2x\__init__.py", line 1, in <module>
    from .utils import Waifu2x
  File "C:\nunif\waifu2x\utils.py", line 3, in <module>
    import torch
  File "F:\3\envs\nunif\lib\site-packages\torch\__init__.py", line 831, in <module>
    from .functional import *  # noqa: F403
  File "F:\3\envs\nunif\lib\site-packages\torch\functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\modules\__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\modules\linear.py", line 7, in <module>
    from .. import functional as F
  File "F:\3\envs\nunif\lib\site-packages\torch\nn\functional.py", line 18, in <module>
    from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
  File "F:\3\envs\nunif\lib\site-packages\torch\_jit_internal.py", line 39, in <module>
    import torch.distributed.rpc
  File "F:\3\envs\nunif\lib\site-packages\torch\distributed\__init__.py", line 56, in <module>
    from .distributed_c10d import *  # noqa: F403
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
EOFError: marshal data too short
```

**Comment by nagadomi** [comment]
.pyc (python compiled bytecode) is corrupted.
Make sure that the disk is not full.
Then search for `*.pyc` under `nunif` directory and delete all of them.
