### ISSUE TITLE
Is it possible to run on 2 GPUs? Can I run on different NVIDIA and intel video cards?

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#49]
![2023-07-01_13-44-42](https://github.com/nagadomi/nunif/assets/49092250/260fdb4f-bb30-4113-9fe5-5ca6b5fc1f76)

```python
(venv) F:\nunif>python -c "from openvino.runtime import Core; print(Core().available_devices)"
['CPU', 'GPU.0', 'GPU.1']

(venv) F:\nunif>python -m waifu2x.web --no-size-limit --cache-ttl 120 --cache-dir F:\nunif\waifu2x\cache --tile-size 400 -g 0 1
F:\nunif\venv\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "C:\Users\tchot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tchot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\nunif\waifu2x\web\__main__.py", line 9, in <module>
    from .server import main
  File "F:\nunif\waifu2x\web\server.py", line 154, in <module>
    command_args, config, art_ctx, art_scan_ctx, photo_ctx, cache, cache_gc = setup()
  File "F:\nunif\waifu2x\web\server.py", line 135, in setup
    art_ctx.load_model_all(load_4x=False)
  File "F:\nunif\waifu2x\utils.py", line 142, in load_model_all
    self._load_model("scale", -1)
  File "F:\nunif\waifu2x\utils.py", line 74, in _load_model
    self.scale_model = self.load_model_by_name("scale2x.pth")
  File "F:\nunif\waifu2x\utils.py", line 55, in load_model_by_name
    return load_model(path.join(self.model_dir, filename),
  File "F:\nunif\nunif\models\utils.py", line 53, in load_model
    model = create_model(data["name"], device_ids=device_ids, **data["kwargs"])
  File "F:\nunif\nunif\models\register.py", line 43, in create_model
    model = data_parallel_model(model, device_ids)
  File "F:\nunif\nunif\models\register.py", line 25, in data_parallel_model
    model = nn.DataParallel(model, device_ids=device_ids)
  File "F:\nunif\venv\lib\site-packages\torch\nn\parallel\data_parallel.py", line 145, in __init__
    _check_balance(self.device_ids)
  File "F:\nunif\venv\lib\site-packages\torch\nn\parallel\data_parallel.py", line 25, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "F:\nunif\venv\lib\site-packages\torch\_utils.py", line 678, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "F:\nunif\venv\lib\site-packages\torch\_utils.py", line 678, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "F:\nunif\venv\lib\site-packages\torch\_utils.py", line 659, in _get_device_attr
    return get_member(torch.cuda)
  File "F:\nunif\venv\lib\site-packages\torch\_utils.py", line 678, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "F:\nunif\venv\lib\site-packages\torch\cuda\__init__.py", line 398, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```

**Comment by nagadomi** [comment]
Two or more NVIDIA GPUs can be used.
However, Intel HD Graphics does not support CUDA, so it cannot be used.

**Comment by My12123** [comment]
Is it possible to use this for intel? https://github.com/intel/intel-extension-for-pytorch and https://github.com/vosen/ZLUDA

**Comment by nagadomi** [comment]
Intel HD Graphics is very slow compared to RTX series, so even if you can use it, it won't improve anything.

Also I can support xpu but cannot run it in a mixed environment.
In other words, you need to run the NVIDIA GPU process and the Intel GPU process separately.

It almost meaningless and I don't think anyone will use it.
